name: main
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Node Install Dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Serverless Deploy
        env:
          EFFORTLESSPT_LOAD_TEST_API_KEY: ${{ secrets.EFFORTLESSPT_LOAD_TEST_API_KEY}}
        run: |
          npm run typescript-compile
          npm run build-load-test
          npm run deploy
